spring.datasource.url=JDBC:mysql:localhost:3306/kumaliza_app
spring.datasource.username=root
spring.datasource.password=rickmassas

spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/api/v1.0